development:
  adapter: mysql
  database: carlog_dev
  username: root
  password: 
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: carlog_test
  username: root
  password:
  pool: 5
  timeout: 5000

production:
    development
